import React from "react";
import { Row, Col, Card } from "react-bootstrap";

// components
import PageTitle from "../../../components/PageTitle";
import Table from "../../../components/Table";

//dummy data
// import { records as data } from "../../tables/data";
import userImg from "../../../assets/images/users/avatar-3.jpg";

const records = [
  {
    id: 1,
    img: userImg,
    name: "Burt",
    group: "Fania Fashion",
    shop: "Chawkbazar Vendor shop...",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 2,
    img: userImg,
    name: "Bruno",
    group: "	Hoppister",
    shop: "Chawkbazar Vendor shop...",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 3,
    img: userImg,
    name: "Alvarado",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 4,
    img: userImg,
    name: "Lilia",
    group: "FVintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 5,
    img: userImg,
    name: "Amanda",
    group: "	Hoppister",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 6,
    img: userImg,
    name: "Alexandra",
    group: "FaVintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 7,
    img: userImg,
    name: "Diana",
    group: "Fa	Hoppister",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 8,
    img: userImg,
    name: "Goodman",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 9,
    img: userImg,
    name: "Edith",
    group: "	Hoppister",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 10,
    img: userImg,
    name: "Juana",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 11,
    img: userImg,
    name: "Fitzgerald",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 12,
    img: userImg,
    name: "Madden",
    group: "Fa	Hoppister",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 13,
    img: userImg,
    name: "Jewell",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 14,
    img: userImg,
    name: "Kerr",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 15,
    img: userImg,
    name: "Washington",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 16,
    img: userImg,
    name: "Audrey",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 17,
    img: userImg,
    name: "Allison",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 18,
    img: userImg,
    name: "Holder",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 19,
    img: userImg,
    name: "Atkinson",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 20,
    img: userImg,
    name: "Delaney",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 21,
    img: userImg,
    name: "Myrna",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 22,
    img: userImg,
    name: "Erna",
    group: "	Hoppister",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 23,
    img: userImg,
    name: "Fannie",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 24,
    img: userImg,
    name: "Melody",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 25,
    img: userImg,
    name: "Letitia",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 26,
    img: userImg,
    name: "Nina",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 27,
    img: userImg,
    name: "Byrd",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 28,
    img: userImg,
    name: "Chen",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 29,
    img: userImg,
    name: "Alexandria",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 30,
    img: userImg,
    name: "Page",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 31,
    img: userImg,
    name: "Clare",
    group: "FVintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 32,
    img: userImg,
    name: "Lindsey",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 33,
    img: userImg,
    name: "Oconnor",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 34,
    img: userImg,
    name: "Maldonado",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 35,
    img: userImg,
    name: "Day",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 36,
    img: userImg,
    name: "Collier",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 37,
    img: userImg,
    name: "Jeannette",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 38,
    img: userImg,
    name: "Wallace",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 39,
    img: userImg,
    name: "Mcfadden",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 40,
    img: userImg,
    name: "Chrystal",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 41,
    img: userImg,
    name: "Leila",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 42,
    img: userImg,
    name: "Madelyn",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 43,
    img: userImg,
    name: "Peck",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 44,
    img: userImg,
    name: "Garrett",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 45,
    img: userImg,
    name: "Kramer",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 46,
    img: userImg,
    name: "Lane",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 47,
    img: userImg,
    name: "Merritt",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 48,
    img: userImg,
    name: "Margarita",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 49,
    img: userImg,
    name: "Leigh",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 50,
    img: userImg,
    name: "Coleman",
    group: "Vintgae",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 51,
    img: userImg,
    name: "Alexander",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 52,
    img: userImg,
    name: "Tanisha",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 53,
    img: userImg,
    name: "Crane",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 54,
    img: userImg,
    name: "Carmella",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 55,
    img: userImg,
    name: "Rosalind",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 56,
    img: userImg,
    name: "Duran",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 57,
    img: userImg,
    name: "Bernard",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 58,
    img: userImg,
    name: "Tate",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 59,
    img: userImg,
    name: "Pearlie",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
  {
    id: 60,
    img: userImg,
    name: "Manning",
    group: "Fania Fashion",
    product_type: "variable",
    price_unit: "$100.00	",
    quantity: "720",
    status: "Publish",
    actions: "edit delete",
  },
];

const columns = [
  {
    Header: "Image",
    accessor: "img",
    Cell: ({ cell }: { cell: any }) => (
      <div>
        <img
          className="rounded"
          src={cell.value}
          alt="User"
          width="40"
          height="40"
        />
      </div>
    ),
  },
  {
    Header: "Name",
    accessor: "name",
    Cell: ({ cell }: { cell: any }) => <div>{cell.value}</div>,
  },
  {
    Header: "Product Type",
    accessor: "product_type",
    Cell: ({ cell }: { cell: any }) => <div>{cell.value}</div>,
  },
  {
    Header: "Price/Unit",
    accessor: "price_unit",
    Cell: ({ cell }: { cell: any }) => <div>{cell.value}</div>,
  },
  {
    Header: "Quantity",
    accessor: "quantity",
    Cell: ({ cell }: { cell: any }) => <div>{cell.value}</div>,
  },
  {
    Header: "Status",
    accessor: "status",
    Cell: ({ cell }: { cell: any }) => (
      <div>
        {cell.value === "Publish" && (
          <button className="btn btn-success btn-sm">Publish</button>
        )}
      </div>
    ),
  },
  {
    Header: "Actions",
    accessor: "actions",
    Cell: ({ cell }: { cell: any }) => (
      <div>
        <>
          <i
            className="bi bi-pencil-square me-4"
            style={{ fontSize: "1.2rem", color: "gray" }}
          ></i>
          <i
            className="bi bi-trash"
            style={{ fontSize: "1.2rem", color: "red" }}
          ></i>
        </>
      </div>
    ),
  },
];

const sizePerPageList = [
  {
    text: "5",
    value: 5,
  },
  {
    text: "10",
    value: 10,
  },
  {
    text: "25",
    value: 25,
  },
  {
    text: "All",
    value: records.length,
  },
];

export default function index() {
  return (
    <>
      <PageTitle
        breadCrumbItems={[
          { label: "Apps", path: "/apps/products" },
          {
            label: "Products List",
            path: "/apps/products",
            active: true,
          },
        ]}
        title={"Products List"}
      />

      <Row>
        <Col>
          <Card>
            <Card.Body>
              <h4 className="header-title">Products</h4>
              <p className="text-muted fs-14 mb-4">
                Search your valuable product.
              </p>
              <Table
                columns={columns}
                data={records}
                pageSize={5}
                sizePerPageList={sizePerPageList}
                isSortable={true}
                pagination={true}
                isSearchable={true}
                nameFor={"Products"}
              />
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </>
  );
}
